#+title: QQ Coin — Tencent’s early virtual currency
#+date: <2018-12-01 00:01>
#+filetags: 
#+OPTIONS: toc:nil
#+OPTIONS: ^:nil
#+OPTIONS: num:nil

There’s a new podcast that I like that covers business in China named [[https://chinaecontalk.libsyn.com/][China Econ Talk]]. One of the episodes briefly mentions a virtual currency developed by Tencent, and there is not much literature covering its success. Within a few years of operation, Tencent’s virtual QQ coin caught the attention of China’s monetary policy experts. The response to virtual currencies in China is familiar to anyone following bitcoin news therefore I thought I would share a brief story about QQ coin — an early virtual currency.

Tencent launched the QQ instant messaging app in 1999 and operates today with close to 1 billion users. During its early growth, Tencent began to develop infrastructure for the digital goods ecosystem. QQ Coin is a project created by Tencent in 2002 that allowed users to purchase digital goods natively within the QQ app. Soon after launch, it became wildly popular and was traded on secondary markets. Gamblers joined the markets to speculate and drive the price of QQ coin. In a few weeks in 2007, QQ Coin’s price rises by 70%.

#+BEGIN_QUOTE
“The Bank will strengthen management of the virtual currencies used in online games and will stay on the lookout for any assault by such virtual currencies on the real economic and financial order.” — Bank of China in 2007
#+END_QUOTE

There was legitimate worry within China’s central banking circle that Tencent’s virtual currency would have an affect on the price of the Yuan.

#+BEGIN_QUOTE
“The QQ coin is challenging the status of the renminbi [yuan] as the only legitimate currency in China.” — Public prosecutor Yang Tao
#+END_QUOTE

The app in 2006 had more than 200 million users, and users began to accept QQ Coin as a legitimate payment system. Tencent designed QQ coins to be used as a native currency within the app, however a creative spontaneous order developed where QQ coins were traded outside the app with real value. The dramatic price increase led by speculation soon drove adoption. Some retailers accepted QQ coin in exchange for real world goods.

Regulators noticed the mania and imposed regulations on Tencent to drive out gamblers and speculators in the QQ ecosystem.

As an early virtual currency, Tencent’s QQ coin seems familiar with the speculation in cryptocurrency.

Learn more:

https://jvwr-ojs-utexas.tdl.org/jvwr/index.php/jvwr/article/viewFile/861/626

https://scholarlycommons.law.wlu.edu/cgi/viewcontent.cgi?referer=https://scholar.google.nl/&httpsredir=1&article=1252&context=wlufac

https://www.atimes.com/atimes/China_Business/HL05Cb01.html

https://www.wsj.com/articles/SB117519670114653518
